### ISSUE TITLE
Add documentation about connecting to JVMs

### ISSUE THREAD

**Issue by gquintana** [aragozin/jvm-tools#33]
As a newcomer, I wish I had read some advice to troubleshoot connection between sjk and my app:
```
$ java -jar sjk.jar ttop -p <pid>
Failed to access MBean server: <pid>
```

* Always use the same user to run sjk as the application: `sudo -u elasticsearch java -jar sjk.jar ttop -p <elasticsearch pid>` and test the connection with jstack before using sjk
* Disable firewalls (iptables and the like): even if you're connecting locally using a PID, sockets are still used for communication.

This would have saved me hours of investigation.

**Comment by aragozin** [comment]
Good point!

I can recall one more reason. Target JVM may have `-Dtmp.io.dir` pointing to non-defalt location.

I would  extend error message.

**Comment by eugeniyk** [comment]
@aragozin you can also add `JDK` installed as prerequisite since with `JRE` it can't attach
```
Java home points to /usr/java/jre1.8.0_66 make sure it is not a JRE path
Failed to add tools.jar to classpath
java.lang.ClassNotFoundException: com.sun.tools.attach.VirtualMachine
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.gridkit.lab.jvm.attach.AttachAPI.<clinit>(AttachAPI.java:45)
	at org.gridkit.lab.jvm.attach.AttachManager.<clinit>(AttachManager.java:73)
	at org.gridkit.jvmtool.JmxConnectionInfo.getMServer(JmxConnectionInfo.java:72)
	at org.gridkit.jvmtool.cmd.GcRepCmd$GcRep.run(GcRepCmd.java:63)
	at org.gridkit.jvmtool.cli.CommandLauncher.start(CommandLauncher.java:133)
	at org.gridkit.jvmtool.SJK.main(SJK.java:11)
```

**Comment by aragozin** [comment]
Error message now points to 
https://github.com/aragozin/jvm-tools/blob/master/sjk-core/docs/TROUBLESHOOTING.md
